### ISSUE TITLE
Error Installing defbro from jwbargsten/misc

### ISSUE THREAD

**Issue by pettefar** [jwbargsten/homebrew-misc#1]
==> Installing defbro from jwbargsten/misc
==> swift build --disable-sandbox --configuration release
Last 15 lines from /Users/nick/Library/Logs/Homebrew/defbro/01.swift:
2021-09-17 20:27:33 +0100

swift
build
--disable-sandbox
--configuration
release

error: terminated(72): /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH

**Comment by jwbargsten** [comment]
Somehow I missed this issue. Is it still relevant?

**Comment by pettefar** [comment]
I can’t remember.

**Comment by pettefar** [comment]
Can’t remember what this was.
