### ISSUE TITLE
Build arm64 binary too

### ISSUE THREAD

**Issue by rgl** [jwbargsten/homebrew-misc#6]
It would be nice to have arm64 binaries too.

FYI, [cirrus ci](https://cirrus-ci.org/) supports arm64 builds. You can see my example at https://github.com/rgl/security-add-trusted-cert/blob/main/.cirrus.yml.

**Comment by jwbargsten** [comment]
Yeah, if you look at how homebrew is working, then you realise that github (actions) is the the only option to get your own tap working. You can deviate, but that comes with a considerable amount of hacking.

However, good news, perhaps beginning 2024 github will provide m1 support.

And even more good news: I found a way to add M1/arm64 bottles to my pipeline: I compile the bottles locally and add the bottle archive to the bottles built by the pipeline.

It should work now for ventura.
